import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "./fonts/Inter-Bold.ttf",
      weight: '700',
      style: 'bold'
    },{
      path: "./fonts/Inter-Regular.ttf",
      weight: '400',
      style: 'regular'
    }
  ],
  variable: "--font-inter"
})

const rivage = localFont({
  src: [
    {
      path: "./fonts/BeauRivage-Regular.ttf",
      weight: '400',
      style: 'regular'
    }
  ],
  variable: "--font-rivage"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${rivage.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
